Created the basic backend/fronend and added  "Create" and "Read" features
crvzybird/ess-cardapio pull request #32
Opened 2022-05-03 01:55 UTC by costa402

2022-05-03 04:22 UTC, leehmaciel requested changes

2022-05-03 04:22 UTC, leehmaciel commented on projeto/client/src/Add.js
> +const Add = (props) => {
Hey @costa402 , 
can you change props to the actual variables? and change on lines 7 and 13 as well. 

Thanks

2022-05-03 04:22 UTC, leehmaciel commented on projeto/server/database.sql
> +    item_description VARCHAR(200)
Hey @costa402 ,
it's not necessary to declare as `item_[column name]` anymore,  only as `column name` like `name VARCHAR(50)`. Can you remove them?
Thanks

2022-05-04 13:59 UTC, costa402 reviewed
Did some changes to fit the review sent. I'm not so sure on what you ment on that comment on the Add.js file so it would be nice if you could take a look at that

2022-05-04 18:11 UTC, leehmaciel approved these changes

2022-05-04 18:12 UTC, merged